version: '3'
services:
  mysql8:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'yHD9xA4uXfGJ5v4d'
      MYSQL_DATABASE: 'dba'
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql8/data:/var/lib/mysql
  postgres16:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 'yHD9xA4uXfGJ5v4d'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'dba'
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres16/data:/var/lib/postgresql/data
  redis7:
    image: redis:7.2-alpine
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6379:6379"
    volumes:
      - ./storage/redis7/data:/data
      - ./redis.conf:/opt/redis.conf
    command: redis-server /opt/redis.conf